name: req_res_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.3
  go_router: ^17.1.0
  google_fonts: ^8.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pinput: ^6.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
